apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mesh-agent
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "watch"]
  - apiGroups: [ "" ]
    resources: [ "gateway" ]
    verbs: [ "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices", "destinationrules", "envoyfilters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["mesh-manager.meshmanager.com"]
    resources: ["istioroutes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["mesh-manager.meshmanager.com"]
    resources: ["istioroutes/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["mesh-manager.meshmanager.com"]
    resources: ["istioroutes/finalizers"]
    verbs: ["update"]